# Setup
title:        FITMER
tagline:      Interval Fitness Timer
baseurl:      ""
paginate:     1
locale:       "en"
favicon:      assets/favicon.ico

# About/contact
author:
  name:       Vivchar Vitaly
  url:        https://vk.com/vivchar

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
